APP_NAME = "NeuralRetail AI"

PRIMARY_COLOR = "#2563EB"
SECONDARY_COLOR = "#06B6D4"

SUCCESS = "#10B981"
WARNING = "#F59E0B"
DANGER = "#EF4444"

CURRENCY = "$"
DATE_FORMAT = "%d-%m-%Y"

PAGE_LAYOUT = "wide"
PAGE_ICON = "🛒"